#!/usr/bin/env bash
set -e

cd "$(dirname "$0")/.."

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle check >/dev/null 2>&1  || {
    bundle install --quiet --without production
  }
fi
